const {Event} = require('../models');

const eventData = [
    {
        title: 'Date night for Mum and Dad!',
        date: '2023-11-23',
        start_time: '6:00',
        finish_time: '8:00',
        duration: 2,
        description: 'test event 1 description',
        status: 'available',
        created_by: 1,
        accepted_by: 2
    }, 
    {
        title: 'Movie night, anyone help!?',
        date: '2023-11-30',
        start_time: '15:00',
        finish_time: '18:00',
        duration: 3,
        description: 'test event 2 description',
        status: 'accepted',
        created_by: 1,
    }, 
    {
        title: 'Friday night in? Sleepy kids!',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 2,
        description: 'test event 3 description',
        status: 'available',
        created_by: 2,
    }, 
    {
        title: 'Please help! Last minute event!',
        date: '2023-11-23',
        start_time: '6:00',
        finish_time: '8:00',
        duration: 2,
        description: 'test event 4 description',
        status: 'available',
        created_by: 3,
        accepted_by: 2,
    }, 
    {
        title: 'Work function, anyone free?',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '23:00',
        duration: 4,
        description: 'random text',
        status: 'available',
        created_by: 2,
    }, 
    {
        title: 'Birthday dinner, free pizza!',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 3,
        description: 'random text',
        status: 'available',
        created_by: 5,
    }, 
    {
        title: 'Anyone free Saturday?',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 3,
        description: 'test event 3 description',
        status: 'available',
        created_by: 5,
    }, 
    {
        title: 'Quick dinner date :)',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 2,
        description: 'test event 3 description',
        status: 'available',
        created_by: 5,
        accepted_by: 2
    }, 
    {
        title: 'Quick local dinner, we have Netflix :)',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 2,
        description: 'test event 3 description',
        status: 'available',
        created_by: 5,
        accepted_by: 2
    }, 
    {
        title: 'House inspection, anyone free to mind Carl?',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 2,
        description: 'test event 3 description',
        status: 'available',
        created_by: 2,
    }, 
    {
        title: 'Going to Theatre, anyone free?',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 2,
        description: 'test event 3 description',
        status: 'available',
        created_by: 2,
    }, 
    {
        title: 'Wedding anniversary, anyone free?',
        date: '2023-11-29',
        start_time: '19:00',
        finish_time: '21:00',
        duration: 2,
        description: 'test event 3 description',
        status: 'available',
        created_by: 2,
    }, 
];

const seedEvents = () => Event.bulkCreate(eventData);

module.exports = seedEvents;